### ISSUE TITLE
shouldn't the title be "Vibration API (Second Edition)"?

### ISSUE THREAD

**Issue by dret** [w3c/vibration#14]
i am trying to track the W3C TR space and it seems that usually, editions are made identifiable so that it's possible to refer to both the stable published REC and the updated version. https://www.w3.org/TR/webstorage/ would be one such example.

**Comment by dontcallmedom** [comment]
thanks, I think you're right that's what usually done; it's probably too late to fix the PER, but I've added this to the draft in preparation for the publication as Rec.
