### ISSUE TITLE
Privacy considerations

### ISSUE THREAD

**Issue by chaals** [w3c/vibration#2]
Vibration can be used in conjunction with other techniques to enhance fingerprinting.

Vibration is also often externally visible, so causing a device to vibrate can be used by a third party able to observe locally to identify the device in question.

**Comment by chaals** [comment]
(So it would be good to put a privacy considerations section into the spec)

**Comment by anssiko** [comment]
Initial input from @lknik: https://lists.w3.org/Archives/Public/public-device-apis/2016Feb/0053.html

**Comment by lknik** [comment]
I suggest working with the following. Please let me know if this is fine. 

"Vibration API is not a source of data on its own and as such is not producing any data possible to consume on the Web. However, it is known that it can serve as a source of events for other APIs. In particular, it is known that certain sensors such as accelerators or gyroscopes are prone to tiny imperfections during their manufacturing. As such, they provide a fingerprinting surface and it is possible to use Vibration API to fingerprint a user's device. In this sense, Vibration API provides an indirect privacy risk, in conjunction with other mechanisms.

Additionally, in case the user intends to remain anonymous, causing a device to vibrate might be visible to external physical observers.  "

**Comment by chaals** [comment]
I think instead of "…it is possible to use Vibration API to fingerprint…" we should say something like "…Vibration API as part of a set of tools can be used to fingerprint…"

I would leave out the "in case the user intends to remain anonymous". It's pretty much a given in any scenario where you are concerned about privacy that you're concerned about who can identify you, no?

(I could do more editing if you like, but I like the basic thrust of the text)

**Comment by lknik** [comment]
Hi,

Of course, feel free to edit...  "as part of a set of tools" sounds equally
fine as "in conjunction with..." etc ;)
Aren't "tools"  more ambiguous here?

But I would suggest to not use any "obvious gut feeling". Privacy and
anonymity aren't the same ;)
I would suggest to keep that if possible

2016-02-12 16:14 GMT+01:00 chaals notifications@github.com:

**Comment by anssiko** [comment]
Here's the proposal for the security and privacy consideration section based on @lknik's input: https://github.com/anssiko/vibration/commit/48489c54e0b7ed80900e0906fa79803c8fa77069

I only did some minor editorial tweaks.

**Comment by anssiko** [comment]
Hearing no concerns, assuming this issue has been addressed by 48489c54e0b7ed80900e0906fa79803c8fa77069 and ad43bf892063ea3695baff3704b3dd67ca492822.

**Comment by lknik** [comment]
Well,

On the other hand, shouldn't we wait for input from PING? But we could
decide that the current form is acceptable, and many issues that may
relate, but in fact relate to other sensors ("reading" functionality) will
be addressed elsewhere. We do indeed point out that this API only
generates.

If we assume it's fine, I'll go with Ambient Light next.

2016-04-26 9:05 GMT+01:00 Anssi Kostiainen notifications@github.com:
