### ISSUE TITLE
Internationalization Checklist

### ISSUE THREAD

**Issue by anssiko** [w3c/vibration#38]
# Internationalization Checklist

The [Short i18n review checklist](https://w3c.github.io/i18n-drafts/techniques/shortchecklist) document is structured into the following sections. Considerations deemed not applicable are marked as "N/A", and those considered relevant are expanded further.

- ### If the spec or its implementation contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc)

N/A

This API allows explicit user mediation through a native UI, but does not specify or control any natural language text associated with such a UI. That is an implementation detail.

Specifically, the API design allows a conformant implementation to show a UI to ask the user for permission to choose to allow or deny vibration on first invocation on a per-origin basis. Implementers who choose to use such a UI are expected to localize any strings and consider base direction to ensure proper presentation.

(The recommended mechanism is to use user activation gating instead. That means the user must interact with the site, with both first and third-party contexts considered separately, to allow a site to vibrate. Sticky activation requires an explicit click, tap, or press of a key. Specifically, scrolling past an iframe does not count as a user activation.)

- ### If the spec or its implementation allows content authors to produce typographically appealing text, either in its own right, or in association with graphics.
N/A

- ### If the spec or its implementation allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc.
N/A

- ### If the spec or its implementation allows searching or matching of text, including syntax and identifiers
N/A

- ### If the spec or its implementation sorts text
N/A

- ### If the spec or its implementation captures user input
N/A

- ### If the spec or its implementation deals with time in any way that will be read by humans and/or crosses time zone boundaries

The API uses milliseconds as a unit of time to express the length of vibration pattern entries.

- ### If the spec or its implementation allows any character encoding other than UTF-8
N/A

- ### If the spec or its implementation defines markup
N/A

- ### If the spec or its implementation deals with names, addresses, time & date formats, etc
N/A

- ### If the spec or its implementation describes a format or data that is likely to need localisation
N/A

- ### If the spec or its implementation makes any reference to or relies on any cultural norms
N/A

**Comment by himorin** [comment]
+1 to go, also for 1st point, since everything are performed behind platform (or mobile browser) but not through via this API, I suppose we could set as N/A with something like, this API allows explicit user mediation through a native UI to user per implementation decision, since we don't control anything about UI behavior behind API interface.

**Comment by anssiko** [comment]
Thank you @himorin for your review and suggestions. I adjusted the first point to "N/A" and attempted to expand the elaborate response based on your suggestion.
